fix: add retry logic for server deployment commands in workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,5 +1,3 @@
-name: Deploy to Server
-
 on:
   push:
     branches:
@@ -7,7 +5,6 @@ on:
 
 jobs:
   build:
-#    runs-on: ubuntu-latest
     runs-on: self-hosted
 
     steps:
@@ -37,4 +34,17 @@ jobs:
         echo "$SSH_PRIVATE_KEY" > private_key
         chmod 600 private_key
         rsync -avz -e "ssh -i private_key -p ${{ vars.SERVER_PORT }}" --exclude='.git' --exclude='node_modules' ./ ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.DEPLOY_PATH }}
-        ssh -i private_key -p ${{ vars.SERVER_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo npm install -g pm2 && pm2 update && cd ${{ vars.DEPLOY_PATH }} && npm install && pm2 restart sylent-x-api || pm2 start index.js --name sylent-x-api --update-env --watch"
+        
+        RETRY_COUNT=0
+        MAX_RETRIES=5
+        SLEEP_TIME=30
+
+        until ssh -i private_key -p ${{ vars.SERVER_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo npm install -g pm2 && pm2 update && cd ${{ vars.DEPLOY_PATH }} && npm install && pm2 restart sylent-x-api || pm2 start index.js --name sylent-x-api --update-env --watch"; do
+          RETRY_COUNT=$((RETRY_COUNT+1))
+          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+            echo "Max retries reached. Exiting."
+            exit 1
+          fi
+          echo "Command failed. Retrying in $SLEEP_TIME seconds..."
+          sleep $SLEEP_TIME
+        done
